on: push

env:
  BuildConfiguration: "Release"
  BuildPlatform: "any cpu"
  Parameters.RestoreBuildProjects: "**/*.csproj"
  Parameters.TestProjects: "**/*[Tt]ests/*.csproj"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
      
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 10.16.3

      - run: npm install TailwindTraders.Website/Source/Tailwind.Traders.Web/ClientApp          
         
      - run: dotnet restore TailwindTraders.Website/Source/Tailwind.Traders.Web.sln

      - run: dotnet build TailwindTraders.Website/Source/Tailwind.Traders.Web.sln
