on: push

env:
  BuildConfiguration: "Release"
  BuildPlatform: "any cpu"
  Parameters.RestoreBuildProjects: "**/*.csproj"
  Parameters.TestProjects: "**/*[Tt]ests/*.csproj"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 10.16.3

      - run: |
          #cd TailwindTraders.Website/Source/Tailwind.Traders.Web/ClientApp
          npm install
        #          workingDir: TailwindTraders.Website/Source/Tailwind.Traders.Web/ClientApp
         
      - run: dotnet restore .\TailwindTraders.Website\Source\Tailwind.Traders.Web.sln
        #projects: '$(Parameters.RestoreBuildProjects)'

      - run: dotnet build .\TailwindTraders.Website\Source\Tailwind.Traders.Web.sln
        #  projects: '$(Parameters.RestoreBuildProjects)'
        #  arguments: '--configuration $(BuildConfiguration)'
