on: push
name: CI Build

env:
  BuildConfiguration: "Release"
  BuildPlatform: "any cpu"
  Parameters.RestoreBuildProjects: "**/*.csproj"
  Parameters.TestProjects: "**/*[Tt]ests/*.csproj"

jobs:
  build:
    strategy:
      matrix:
        runner: [ubuntu]
    runs-on: ${{ matrix.runner }}-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
      
      - name: Clone repo
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 10.16.3

      - name: npm install
        run: npm install TailwindTraders.Website/Source/Tailwind.Traders.Web/ClientApp          
         
      - name: dotnet restore
        run: dotnet restore TailwindTraders.Website/Source/Tailwind.Traders.Web.sln

      - name: dotnet build
        run: dotnet build TailwindTraders.Website/Source/Tailwind.Traders.Web.sln

  container:
    runs-on: ubuntu-latest
    container: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
      
      - name: Clone repo
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 10.16.3

      - name: npm install
        run: npm install TailwindTraders.Website/Source/Tailwind.Traders.Web/ClientApp          
         
      - name: dotnet restore
        run: dotnet restore TailwindTraders.Website/Source/Tailwind.Traders.Web.sln

      - name: dotnet build
        run: dotnet build TailwindTraders.Website/Source/Tailwind.Traders.Web.sln
